### ISSUE TITLE
organizing images for post

### ISSUE THREAD

**Issue by k-kipruto** [the-mvm/the-mvm.github.io#18]
looks like /assets/img/posts will look like a mess when you have a dozen blog posts, What I did was to organize was to create folder for each post with name as  *.md. Then for front matter just edit  to  img: posts/{yyyy/mm/dd}filename/
I know I should have been creating pull request but my code in fork is quite messy. will do so in for future fixes.

**Comment by amaynez** [comment]
I agree, all the images in a single directory can become quite messy, I started to name them according to the post, but I think your solution is much better. I will try to retrofit it.

**Comment by amaynez** [comment]
Done, I took your suggestion but left YYYYMMDD without the intermediate backslashes so not to have too many subdirectories.
[See commit here](https://github.com/the-mvm/the-mvm.github.io/commit/c8edd47f88d5daa08d6c096cbad584db2630945c)
